name: KeepItems
main: net.robinjam.bukkit.keepitems.KeepItems
version: ${project.version}
author: robinjam

permissions:
  keep-items.*:
    description: Allows the player to keep both their level, their progress towards the next level and their armour upon death
    default: true
    children:
      keep-items.armor: true
      keep-items.level: true
      keep-items.progress: true
  
  keep-items.armor:
    description: Allows the player to keep their armour upon death
    default: false
  
  keep-items.level:
    description: Allows the player to keep their current level upon death
    default: false
  
  keep-items.progress:
    description: Allows the player to keep their progress towards the next level upon death (requires keep-items.level)
    default: false
